### ISSUE TITLE
笔记本调整亮度失效

### ISSUE THREAD

**Issue by 2218675712** [yingDev/WGestures2-mac-bugs#321]
lua脚本
```
function wgAction(pos,wid,pid,exe,title,mode)
  local result = WG.SetBrightness(pos, 5)
  if(result >= 0) then
    WG.ShowToast('☀'..result..'%', 1000);
  end
end
```

日志
```
System.Exception: Cannot get monitor brightness! NERR_Success
   at YingDev.WGApp.LuaApi.WG.SetBrightness(POINT pt, Int32 percent_abs_or_delta, Boolean isDelta)
System.Exception: Cannot get monitor brightness! NERR_Success
   at YingDev.WGApp.LuaApi.WG.SetBrightness(POINT pt, Int32 percent_abs_or_delta, Boolean isDelta)
System.Exception: Cannot get monitor brightness! NERR_Success
   at YingDev.WGApp.LuaApi.WG.SetBrightness(POINT pt, Int32 percent_abs_or_delta, Boolean isDelta)
System.Exception: Cannot get monitor brightness! NERR_Success
   at YingDev.WGApp.LuaApi.WG.SetBrightness(POINT pt, Int32 percent_abs_or_delta, Boolean isDelta)

```

**Comment by Arizening** [comment]
+1希望尽快修复，软件也好久没有更新了呀

**Comment by csyg1733** [comment]
same issue
